<a href="https://colab.research.google.com/github/MrAStone/3.2.1-DataTypes/blob/master/Innovation.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np


In [14]:
arr = np.array([1,2,3,4,5])
subset = arr[0:6:2]
print(subset)

matrix = np.array([[1,2,3],
                  [4,5,6],
                  [7,8,9]])
row_subset = matrix[0:2,:]
print (row_subset)
col_subset = matrix[:,0:1]
print(col_subset)

[1 3 5]
[[1 2 3]
 [4 5 6]]
[[1]
 [4]
 [7]]
